import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import ApolloClientProvider from "./ApolloClientProvider";
import { CookiesProvider } from 'next-client-cookies/server';
import { cn } from "@/lib/utils";
import UserDataProvider from "./UserDataProvider";

const openSans = Open_Sans({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <CookiesProvider>
        <ApolloClientProvider>
          <UserDataProvider>
            <body
              className={cn(
                "min-h-screen bg-background font-sans antialiased",
                openSans.variable
              )}
            >
              {children}
            </body>
          </UserDataProvider>
        </ApolloClientProvider>
      </CookiesProvider>
    </html>
  );
}
