import type { Metadata } from "next";
import "./globals.css";
import ApolloClientProvider from "./ApolloClientProvider";
import { CookiesProvider } from 'next-client-cookies/server';
import UserDataProvider from "./UserDataProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl">
      <CookiesProvider>
        <ApolloClientProvider>
          <UserDataProvider>
            <body className="min-h-screen flex flex-col bg-background antialiased">
              {children}
            </body>
          </UserDataProvider>
        </ApolloClientProvider>
      </CookiesProvider>
    </html>
  );
}
